- FittedSheetsPod/SheetViewController.swift
Previously when using a large corner radius (> 25) along with `extendBackgroundBehindHandle`, a weird clipping issue would occur because the corner radius was applied to the `pullBarView` which only had a height of 50 pixels (see attached images).
This changes moves the corner radius to the `containerView` when `extendBackgroundBehindHandle` is true, so that both `pullBarView` and the child ViewController's view is clipped.
> Add corner radius to containerView when extending behind handle

- FittedSheetsPod/SheetViewController.swift
Note: The call to `self.setUpChildViewController()` was moved after `self.setUpPullBarView()` to make sure `pullBarView` is already a subview of the container view when we pin the child ViewController's top edge to it's bottom edge (otherwise they won't have a common ancestor at the time of pinning).
> Customization of handle size and top/bottom spacing

- FittedSheetsPod/SheetViewController.swift
Setting the background color to the overlay color in `viewDidLoad` causes the overlay to immediately appear (as opposed to the desired fade in effect).
The `self.view?.window != nil` change is to ensure the view is both loaded and visible. This fixes the fade in in examples such as `ColorExampleViewController`.
> Initialize background color to UIColor.clear so overlay fades in

- README.md
Readme example references `present(controller, animated: false, completion: nil)` when it should be `present(sheetController, animated: false, completion: nil)` as per example before
> Corrected Readme Example Reference Error

- FittedSheetsPod/SheetViewController.swift
UIButtons are already excluded for the gesture recognizer shouldReceive touch delegate. Could we expand that to all UIControls, since the issues also occur with UISlider for instance
> exclude UIControls in shouldReceive touch

- FittedSheets.podspec.json
- FittedSheetsPod/SheetViewController.swift
Previously, Voice Over users were not able to exit the modal. Now anyone can exit by tapping on the pull bar, and it shows up to the screen reader
> Added accessibility to pull bar

- FittedSheetsPod/SheetViewController.swift
This allows you to enable swipe-to-dismiss when the pan gesture starts overtop a UIControl - disabled by default to give priority to the UIControl and thus not begin dismissing the sheet. Useful if you have a full-screen stack view that contains UIButtons for example.
> Support recognizing pan gesture with UIControls

- FittedSheets.xcodeproj/xcshareddata/xcschemes/FittedSheetsPod.xcscheme
This PR adds Carthage support.
It simply makes the FittedSheetsPod scheme shared so it can be persisted into Git and visible to Carthage.
Closes #46
> Carthage support

- FittedSheets/ResizingDemo/ResizingDemo.storyboard
- FittedSheets/ResizingDemo/ResizingDemo.swift
- FittedSheets/ResizingDemo/ResizingExampleViewController.swift
- FittedSheetsPod/SheetSize.swift
- FittedSheetsPod/SheetViewController.swift
We can define height by constant margin from top now.
> Margin resize

- FittedSheetsPod/SheetOptions.swift
- FittedSheetsPod/SheetTransition.swift
- FittedSheetsPod/SheetViewController.swift
These are configurable via the SheetOptions object. I tuned them to be pretty subtle by default, but of course they could also be turned off by default.
If you turn down the dampening, you'll see a design flaw, in that the sheet will bounce up away from the bottom edge of the screen. I couldn't think of an easy way to fix that. With a subtle bounce, I think it looks fine.
In theory, this addresses #6
> Added spring based animation options to the sheet transition animations

- FittedSheetsPod/SheetContentViewController.swift
this pr will move `overflowView.backgroundColor = self.childViewController.view.backgroundColor` line after `setupChildViewController` func in `SheetContentViewController` so viewDidLoad in content vc wont call before setupChildViewController where `sheetViewController` is nil because the child has not parent yet.
> bug-fix not working scrollview

- FittedSheets/SheetViewController.swift
In order to provide a custom statusBar style (useful/ required when presenting the sheet only partially) we have to override `childForStatusBarStyle`
> Setup childForStatusBarStyle

- FittedSheets/SheetViewController.swift
Added a public func 'updateIntrinsicHeight()' that will recalculate the sheet content's intrinsic height and update the sheet to match. resolves #123
> Allow for intrinsic height to be recalculated

- FittedSheets/SheetViewController.swift
Superview constraint are being animated when the resize function is setting the contentViewControllerHeightConstraint. With this commit i am able to remove the 'weird sweeping issue' but i think the we can work more on the animation.
how to reproduce:
1. Create child viewcontroller that have collection/tableview inside it.
2. Present the sheetViewController using present() from view controller.
> Fixes #118

- FittedSheets/SheetOptions.swift
- FittedSheets/SheetViewController.swift
Option to allow override should begin pull gesture. This is needed when we have a header and scroll view is not scrolled top.
> Option to allow override should begin pull gesture

- FittedSheets/SheetViewController.swift
Hello there. In my app some screen supporting different interface orientation like:
```Swift
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
return UIDevice.current.userInterfaceIdiom == .pad ? .all : [.portrait, .portraitUpsideDown]
}
```
So I faced with a problem that `SheetViewController` ignoring `supportedInterfaceOrientations` of a child
I thinks that should be fair enough if `SheetViewController` could inherit supported interface orientations of his child
> Add supportedInterfaceOrientations

- FittedSheets/SheetContentViewController.swift
- FittedSheets/SheetViewController.swift
- README.md
- Currently, only circular corner curves are possible
- This adds support for choosing the corner curve to be continuous if desired
- Support is limited to iOS 13 or later
This was previously #160. See comments there for context on the CI failure.
> Add support for choosing the corner curve

- Demos/DemoControllers/RubberBandDemo.swift
- Demos/ModalDemosViewController.swift
- FittedSheets.xcodeproj/project.pbxproj
- FittedSheets/SheetOptions.swift
- FittedSheets/SheetViewController.swift
Fixes https://github.com/gordontucker/FittedSheets/issues/154
Add option to enable "rubber band", disabled by default to avoid retro-compatibility issues.
Add rubber band effect (based on https://medium.com/thoughts-on-thoughts/recreating-apple-s-rubber-band-effect-in-swift-dbf981b40f35)
Add demo.
https://user-images.githubusercontent.com/4202511/128634657-eadd53bd-8f81-4f6b-b99f-84222530ea30.mp4
> Add rubber band effect.

- Demos/BugVerificationControllers/PresentFullscreenModalCausesDidDismiss.swift
- Demos/BugVerificationsViewController.swift
- FittedSheets.xcodeproj/project.pbxproj
after presenting the sheet, in the content view, when presenting a further view controller using the `modalTransitionStyle` of `.crossDissolve` causes `sheet.didDismiss` to erroneously fire.
any other modalTransitionStyle doesn't have this behavior.
for now, i'm working around by keeping around a flag before i present the child view controller, but i'd like to better understand this and solve it
> Add Bug Verification for presenting a fullscreen modal

- FittedSheets/SheetViewController.swift
If you say `vc.dismissOnPull = true` and `vc.shouldDismiss { _ in false }`, I expect the view controller _not_ to be dismissed when I pull down. (This logic applies to `dismissOnOverlayTap` already.)
This change makes that true. Before, the view controller would be hidden even if `shouldDismiss` returned `false`.
> dismissOnPull obeys shouldDismiss

- FittedSheets/SheetViewController.swift
Hi! 
**Problem**
When I resize the FittedSheets with animation and push viewController at the same time - animation do not working. 
**Fix**
I resolved it when changed 
`self.contentViewController.view.layoutIfNeeded()` to `self.view.layoutIfNeeded()`
Thank you for the greate lib!
> SheetViewController.swift --> resize animation fix
